### ISSUE TITLE
Add scrolling animations

### ISSUE THREAD

**Issue by Electric108** [blackswan3dprinting/blackswan3d.com#29]
-Please embed several images as scrolling animations throughout the [About us page ](https://www.blackswan3d.com/about/)
    -files can be found[Here](https://drive.google.com/drive/folders/1PIgFvwhTpofeyaEowt_DawEF4ad-HCeQ) 
    -prefer to use fade in style of animation found [Here](https://www.vev.design/blog/scroll-animation-examples/)

**Comment by calejvaldez** [comment]
resources
- [fireship.io](https://youtu.be/HZHHBwzmJLk)
- [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll-driven_animations)
- [another fireship.io](https://youtu.be/T33NN_pPeNI?si=wfx2JFxecIgWZGr6)
- [webdev simplified](https://youtu.be/YszONjKpgg4?si=AGMgdaKiWlIyu2Qo)
